# Operator-supplied (see config.env / -var). Everything else is derived from the
# generated topology.auto.tfvars.json — you should not need to edit that by hand.

variable "project_id" {
  type        = string
  description = "GCP project to run the ephemeral field test in. Billing must be enabled."
}

variable "default_region" {
  type    = string
  default = "us-central1"
}

variable "run_id" {
  type        = string
  description = "Unique label for this run; every resource is tagged cloudtest=<run_id> so a `gcloud`-nuke-by-label can clean up even if Terraform state is lost."
}

variable "machine_type" {
  type    = string
  default = "e2-small" # 2 vCPU burstable, ~2GB — enough for a FAST-mode node
}

variable "image" {
  type    = string
  default = "debian-cloud/debian-12"
}

variable "boot_disk_gb" {
  type    = number
  default = 20
}

variable "ttl_minutes" {
  type        = number
  default     = 180
  description = "Hard self-destruct: every VM runs `shutdown -h +ttl` at boot, so even a crashed orchestrator cannot leak a running instance past this. Terraform destroy still removes the (stopped) instances + disks."
}

variable "silt_binary_path" {
  type        = string
  description = "Local path to the freshly-built linux/amd64 silt binary (the orchestrator builds it and Terraform uploads it to GCS). Testing the CURRENT commit, not a release."
}

variable "ssh_pubkey" {
  type        = string
  default     = ""
  description = "Optional: an SSH public key to add to instance metadata. Leave empty to rely on `gcloud compute ssh` over IAP (recommended — no key management, reaches natted nodes too)."
}

variable "budget_amount_usd" {
  type        = number
  default     = 0
  description = "If > 0 and billing_account is set, create a GCP billing budget alarm at this amount as a cost backstop."
}

variable "billing_account" {
  type    = string
  default = ""
}

# ── Injected from topology.auto.tfvars.json (generated by topology.py) ──────────
variable "nodes" {
  type = map(object({
    role   = string
    ip     = string
    zone   = string
    region = string # the region of `zone`; selects the per-region public subnet
    argv   = string # the full `silt ...` command line, or "NATGW"
    # Main-swarm node with NO external IP (egress via Cloud NAT, reached over
    # IAP): zero IN_USE_ADDRESSES quota. Used by the ECONOMY killable stores —
    # ECONOMY=1 SYBILS=8 saturates every region's default 8-IP quota.
    internal_only = optional(bool, false)
  }))
}

variable "public_cidr" { type = string } # legacy/default public CIDR (default region); kept for reference
variable "nat_cidr" { type = string }
variable "region_cidrs" {
  type        = map(string) # region → /24 for that region's public subnet
  description = "One public subnet per region the topology uses (GCP subnets are regional)."
}
variable "swarm_port" { type = number }
variable "relay_port" { type = number }
variable "registry_port" { type = number }

variable "core_on_demand" {
  type        = bool
  default     = true
  description = "Run the CONSENSUS/REGISTRY core (validator + registry roles) as STANDARD (non-preemptible) instances so an RC-gate run isn't disrupted by SPOT preemption; all other roles stay SPOT for cost. Set false for the cheapest all-SPOT shakedown."
}

variable "all_on_demand" {
  type        = bool
  default     = false
  description = "Run EVERY node as STANDARD (non-preemptible). For a CERTIFICATION run: core_on_demand only protects validator+registry, but a cert also needs storage (holds published content), relay (NAT), and adversary (#184) to survive — a mid-run SPOT preemption of store-1 fails publish and cascades into a false FAIL of nearly every flow. e2-small on-demand is ~cents/hr for the whole fleet; overrides core_on_demand when set."
}
