#!/usr/bin/env bash
# gen_report.sh — turn results.jsonl into a shareable report (Markdown + a
# self-contained HTML file). This is the artifact an outside developer hands back
# after running the field test: a per-flow verdict table, then every finding.
set -euo pipefail
FT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESULTS="${RESULTS_JSONL:-$FT_DIR/results.jsonl}"
OUT_MD="${1:-$FT_DIR/report.md}"
OUT_HTML="${2:-$FT_DIR/report.html}"

SILT_COMMIT="$(git -C "$FT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
RUN_ID="${RUN_ID:-unknown}"
BOND_MODE="$(python3 -c "import json;print(json.load(open('$FT_DIR/topology.json'))['meta']['bond_mode'])" 2>/dev/null || echo unknown)"
GEN_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

python3 - "$RESULTS" "$OUT_MD" "$OUT_HTML" "$SILT_COMMIT" "$RUN_ID" "$BOND_MODE" "$GEN_TS" <<'PY'
import json, sys, html
results_path, out_md, out_html, commit, run_id, bond_mode, gen_ts = sys.argv[1:8]

rows = []
try:
    for line in open(results_path):
        line = line.strip()
        if line:
            rows.append(json.loads(line))
except FileNotFoundError:
    pass

order = ["pass", "gap", "fail", "skip"]
counts = {k: sum(1 for r in rows if r["verdict"] == k) for k in order}
graded = [r for r in rows if r["verdict"] != "skip"]
overall = "PASS" if counts["fail"] == 0 and graded else ("FAIL" if counts["fail"] else "NO RESULTS")
sev_rank = {"blocker": 0, "major": 1, "minor": 2, "cosmetic": 3}

# ── Markdown ────────────────────────────────────────────────────────────────
md = []
md.append(f"# silt field-test report\n")
md.append(f"- **run:** `{run_id}`  ·  **silt commit:** `{commit}`  ·  **bond mode:** `{bond_mode}`  ·  **generated:** {gen_ts}")
md.append(f"- **result:** **{overall}**  ·  {counts['pass']} pass / {counts['gap']} gap / {counts['fail']} fail / {counts['skip']} skip\n")
md.append("## Per-flow verdict\n")
md.append("| flow | verdict | severity | elapsed | detail |")
md.append("|------|---------|----------|---------|--------|")
def badge(v): return {"pass":"✅ pass","gap":"⚠️ gap","fail":"❌ fail","skip":"➖ skip"}.get(v, v)
for r in sorted(rows, key=lambda r: r["flow"]):
    el = f"{r['elapsed_s']}s" if r.get("elapsed_s") not in (None, "null") else ""
    md.append(f"| `{r['flow']}` | {badge(r['verdict'])} | {r.get('severity','')} | {el} | {r['detail']} |")
md.append("")
findings = [r for r in rows if r["verdict"] != "pass"]
if findings:
    md.append("## Findings (gaps + failures), most severe first\n")
    for r in sorted(findings, key=lambda r: (sev_rank.get(r.get('severity'),9), r['flow'])):
        md.append(f"### {r['flow']} — {badge(r['verdict'])} ({r.get('severity','')})")
        md.append(f"{r['detail']}\n")
else:
    md.append("_No gaps or failures recorded._\n")
md.append("---\n")
md.append("_Generated by `integration/cloudtest`. The field network is ephemeral and was torn down after this run._")
open(out_md, "w").write("\n".join(md))

# ── self-contained HTML ─────────────────────────────────────────────────────
def h(s): return html.escape(str(s))
color = {"pass":"#1a7f37","gap":"#9a6700","fail":"#cf222e","skip":"#57606a"}
trows = []
for r in sorted(rows, key=lambda r: r["flow"]):
    el = f"{r['elapsed_s']}s" if r.get("elapsed_s") not in (None,"null") else ""
    trows.append(f"<tr><td><code>{h(r['flow'])}</code></td>"
                 f"<td style='color:{color.get(r['verdict'],'#333')};font-weight:600'>{h(r['verdict']).upper()}</td>"
                 f"<td>{h(r.get('severity',''))}</td><td>{h(el)}</td><td>{h(r['detail'])}</td></tr>")
ocolor = {"PASS":"#1a7f37","FAIL":"#cf222e","NO RESULTS":"#57606a"}[overall]
doc = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>silt field-test report — {h(run_id)}</title>
<style>
 body{{font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#1f2328}}
 h1{{margin-bottom:.2rem}} .meta{{color:#57606a;font-size:13px}}
 .result{{display:inline-block;padding:.2rem .6rem;border-radius:6px;color:#fff;background:{ocolor};font-weight:700}}
 table{{border-collapse:collapse;width:100%;margin:1rem 0;font-size:14px}}
 th,td{{border:1px solid #d0d7de;padding:.4rem .6rem;text-align:left;vertical-align:top}}
 th{{background:#f6f8fa}} code{{background:#f6f8fa;padding:.05rem .3rem;border-radius:4px}}
 .tally span{{margin-right:1rem;font-weight:600}}
</style></head><body>
<h1>silt field-test report</h1>
<p class="meta">run <code>{h(run_id)}</code> · silt commit <code>{h(commit)}</code> · bond mode <code>{h(bond_mode)}</code> · {h(gen_ts)}</p>
<p><span class="result">{overall}</span></p>
<p class="tally"><span style="color:#1a7f37">{counts['pass']} pass</span>
<span style="color:#9a6700">{counts['gap']} gap</span>
<span style="color:#cf222e">{counts['fail']} fail</span>
<span style="color:#57606a">{counts['skip']} skip</span></p>
<table><thead><tr><th>flow</th><th>verdict</th><th>severity</th><th>elapsed</th><th>detail</th></tr></thead>
<tbody>{''.join(trows)}</tbody></table>
<p class="meta">Generated by <code>integration/cloudtest</code>. The field network is ephemeral and was torn down after this run.</p>
</body></html>"""
open(out_html, "w").write(doc)
print(f"report: {overall} — {counts['pass']} pass / {counts['gap']} gap / {counts['fail']} fail")
print(f"  {out_md}")
print(f"  {out_html}")
PY
